name: Run VRT

on:
  push:
    paths:
      - "chapter9/**"
  pull_request:
    paths:
      - "chapter9/**"

env:
  REG_NOTIFY_CLIENT_ID: ${{ secrets.TESTCODE_REG_NOTIFY_CLIENT_ID }}
  AWS_BUCKET_NAME: ${{ secrets.TESTCODE_AWS_BUCKET_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chapter9
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 이 값이 없으면 비교를 진행할 수 없다.
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.TESTCODE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TESTCODE_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Install dependencies
        run: npm ci
      - name: Build Storybook
        run: npm run storybook:build
      - name: Run Storycap
        run: npm run vrt:snapshot
      - name: Run reg-suit
        run: echo "REG_NOTIFY_CLIENT_ID: $REG_NOTIFY_CLIENT_ID" && npm run vrt:run
